services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - frontend_network

  backend:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  
  backend_network:
    driver: bridge

